fp16:
  enabled: true
  auto_cast: true
  loss_scale: 0
  loss_scale_window: 1000
  initial_scale_power: 16
  hysteresis: 2
  min_loss_scale: 1

zero_force_ds_cpu_optimizer: false

bf16:
  enabled: false

zero_optimization:
  stage: 3
  offload_optimizer:
    device: cpu
    pin_memory: true
  offload_param:
    device: cpu
    pin_memory: true
  overlap_comm: true
  contiguous_gradients: true
  sub_group_size: 1.0e+7
  reduce_bucket_size: auto
  stage3_prefetch_bucket_size: auto
  stage3_param_persistence_threshold: auto
  stage3_max_live_parameters: 1.0e+7
  stage3_max_reuse_distance: 1.0e+7
  stage3_gather_16bit_weights_on_model_save: true

gradient_accumulation_steps: 1
gradient_clipping: 1.0
steps_per_print: 10
train_micro_batch_size_per_gpu: 1
wall_clock_breakdown: false