compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
    fp16:
      enabled: true
      auto_cast: true
      loss_scale: 0
      loss_scale_window: 1000
      initial_scale_power: 16
      hysteresis: 2
      min_loss_scale: 1
    
    zero_force_ds_cpu_optimizer: false
    
    bf16:
      enabled: false
    
    zero_optimization:
      stage: 3
      offload_optimizer:
        device: cpu
        pin_memory: true
      offload_param:
        device: cpu
        pin_memory: true
      overlap_comm: true
      contiguous_gradients: true
      sub_group_size: 1.0e+7
      reduce_bucket_size: auto
      stage3_prefetch_bucket_size: auto
      stage3_param_persistence_threshold: auto
      stage3_max_live_parameters: 1.0e+7
      stage3_max_reuse_distance: 1.0e+7
      stage3_gather_16bit_weights_on_model_save: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false